### ISSUE TITLE
Brakeman Issue:  Unescaped model attribute

### ISSUE THREAD

**Issue by fitzgerald** [pgharts/trusty-festivity-extension#1]
Unescaped model attribute
                = @event.video.html_safe
Found in app/views/festivity_events/show.html.haml by brakeman

**Comment by danigirl329** [comment]
@fitzgerald I resolved in this commit: https://github.com/pgharts/trusty-festivity-extension/commit/bf34295f83ac2db45e4e1a366f13c95dbd78f14a

= sanitize(@event.video.try(:html_safe))

**Comment by fitzgerald** [comment]
Closing!
